name: contacts_kit
description: "A fast contacts plugin for Flutter with support for Android and iOS"
version: 0.0.1
license: MIT
homepage: https://github.com/NerdyBees/contacts_kit

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.0.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  plugin:
    platforms:
      android:
        package: com.example.contacts_kit
        pluginClass: ContactsKitPlugin
      ios:
        pluginClass: ContactsKitPlugin
      web:
        pluginClass: ContactsKitWeb
        fileName: contacts_kit_web.dart
